input.onButtonEvent(Button.A, input.buttonEventClick(), function () {
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
    basic.showNumber(0)
})
